### ISSUE TITLE
Book Info improvements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1832]
- [ ] Handle books with editors but no authors: pressbooks/ideas#134 [X-Large]
- [ ] Add fields for ancillary materials: pressbooks/ideas#169 [Large]
- [ ] Investigate how contributor lists might be imported/exported: pressbooks/pressbooks#1824 [Small]
- [ ] Give more options for contributor display: https://github.com/pressbooks/ideas/issues/326
