### ISSUE TITLE
[Hackathon] Surface more information about contributors in the book and book homepage

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2096]
Will hold a 2 1/2 day hackathon from August 2-4 to focus on the following:

**Feature description:**
DONE:
- [x] Change contributor page to allow user entry (and sanitize inputs) for Name, square profile picture (upload image or choose from media library) with size contraints, text bio (rich text input -- allows links, italics, bold, but not other html tags for now), Website (URL input), Twitter (URL input), LinkedIn (URL input), GitHub (URL input). Any text that has been already entered in to the current 'description' field provided for contributors should be preserved and moved to the text bio field, if possible.
- [x] Change user profile page to match inputs described above. Remove unneccesary fields. https://github.com/pressbooks/pressbooks/pull/2295
- [x] When an existing user is added to a book with the role of (or has their role increased to that of) contributor or higher, make sure a 'contributor' entry is created for them and matches at time of creation. 
- [x] Create an 'about the contributor' stub/page for each contributor which displays the info provided above in attractive way

TODO:
- [ ] #2312
- [ ] #2311
- [ ] https://github.com/pressbooks/pressbooks-book/issues/832
- [ ] #2314
- [ ] https://github.com/pressbooks/pressbooks-book/issues/831
- [ ] Allow users to associate their Pressbooks profile with an ORCID ID (stretch goal): https://github.com/pressbooks/pressbooks/issues/1500

Context: https://docs.google.com/document/d/1b-YsRqRERAEsz3hwNWAT24CGgt-lL84Ee5BQ3PsEp9s/edit#bookmark=id.85aqxibgch6s

**Comment by hughmcguire** [comment]
* generate a "Contributor" page in the book that is a styled list of all contributors & their info.

**Comment by NMSalmon** [comment]
I'm very excited for this revamp! Two related questions/ideas, if they're welcome here (otherwise please ignore!):

1.  Would this affect the way that the dashboard view of the contributors feature operates? (Currently, my "contributors" list will display the number of pages affiliated with each author, but if you click on that count hyperlink, it just takes you to a blank page that says "0 posts" rather than showing you who authored which chapter.)

2. Is there a way to customize what information appears for a given contributor appears on a page-by-page basis without making multiple different slugs for that contributor? (I'm thinking about contexts where a person's role in relation to the chapter might shift. For instance, I'm working with a faculty resource text where some chapters might include in the author field "Naomi Salmon, English 200 Instructor" while others would say "Naomi Salmon, Writing Center Instructor." The same might apply for chapters where the authors each took on a different authorial/editorial role.)

**Comment by SteelWagstaff** [comment]
Nice PoC from Rebus Community:
![Screenshot from 2021-06-21 11-31-53](https://user-images.githubusercontent.com/13485451/122810532-521bc600-d284-11eb-9955-f3ed119f0452.png)

**Comment by SteelWagstaff** [comment]
See https://github.com/WordPress/WordPress/blob/master/wp-admin/user-edit.php for the default WordPress page that we want to replace + https://github.com/pressbooks/pressbooks/blob/4cdee460dcc1800c7437297c9c45574650b6d814/inc/class-contributors.php#L249-L322 to see how our contributor feature currently pulls/updates information from the user profile.

**Comment by SteelWagstaff** [comment]
In January 2018, Dac & Ned added a basic UI which allows users to save contributor terms from the taxonomy as authors, editors, translators, reviewers, illustrators, or contributors in Book Info or authors in chapters, front & back matter: https://github.com/pressbooks/pressbooks/pull/1020. To do this, they added a contributor class: https://github.com/pressbooks/pressbooks/pull/1031, refactored getBookinformation() behaviour: https://github.com/pressbooks/pressbooks/pull/1038 and registered contributors as a new ‘taxonomy’: https://github.com/pressbooks/pressbooks/pull/1048. They also moved the contributor UI interface under ‘Book info’ in the book dashboard: https://github.com/pressbooks/pressbooks/pull/1351/files. 

See https://wordpress.org/support/article/taxonomies/ for more on what a taxonomy is within WordPress.

**Comment by SteelWagstaff** [comment]
@dalcin and @richard015ar -- when it comes to editing the bio field, here's how we added support for a very simple set of accepted HTML tags to the glossary terms: https://github.com/pressbooks/pressbooks/pull/1559/files

For the profile picture, we want to let the user upload an image or choose one from the media gallery and then provide them with a cropping option to ensure that it's a square. See the video below for a demonstration of the precise functionality desired from the existing site icon upload feature already present in Aldine (inherited from core WordPress):

https://user-images.githubusercontent.com/13485451/127922726-c76585c6-8783-4ba6-a29c-ec7a3a276ede.mp4

See https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-custom-image-header.php for sample implementation, I think?

We want to modify the [addBlogUser function](https://github.com/pressbooks/pressbooks/blob/82cc855787bb06906911122f0fa191c26ffa564d/inc/class-contributors.php#L255-L277) so that it is trigged in two cases: 1) whenever a new user is added to a book with a role of contributor, author, editor, or administrator, and 2) whenever user who was previously in a book with a subscriber or anonymous role has their role changed to contributor or greater. When this addBlogUser function is triggered it should create a new contributor in that book with all available relevant information from that user's profile, not just first/last name (should attempt to get and display first/last name, bio, gravatar image, website, Twitter, LinkedIn, GitHub URLs).

Finally, I don't think we ever want updates to a user's profile to alter/update their contributor information. That means removing this function entirely, I think: https://github.com/pressbooks/pressbooks/blob/82cc855787bb06906911122f0fa191c26ffa564d/inc/class-contributors.php#L280-L323. It's possible that we might want to keep the user name update component, but we definitely shouldn't override any other information for contributors when a user profile is updated.

**Comment by SteelWagstaff** [comment]
@NMSalmon we just started working on this issue in a whole team Hackathon. Still very early, but some tentative answers.
> 1. Would this affect the way that the dashboard view of the contributors feature operates? (Currently, my "contributors" list will display the number of pages affiliated with each author, but if you click on that count hyperlink, it just takes you to a blank page that says "0 posts" rather than showing you who authored which chapter.)

Yes. We plan to overhaul/improve the contributor dashboard view as part of these changes.

> 2. Is there a way to customize what information appears for a given contributor appears on a page-by-page basis without making multiple different slugs for that contributor? (I'm thinking about contexts where a person's role in relation to the chapter might shift. For instance, I'm working with a faculty resource text where some chapters might include in the author field "Naomi Salmon, English 200 Instructor" while others would say "Naomi Salmon, Writing Center Instructor." The same might apply for chapters where the authors each took on a different authorial/editorial role.)

There's not an easy way to do this within a given book without creating multiple contributors in that book. You can and will definitely be able to modify/customize a contributor's information across multiple books on the same network, however, even if they're derives from the same network 'user'.

**Comment by SteelWagstaff** [comment]
I think we'd like to revise the book home page to show the name of a primary contributor/contributors (should be editor(s), author(s), or translator(s). Below that we want to show a new Contributors block that shows the profile picture of the first 4 contributors which have images added to their profile and then a circle with the number of additional contributors who do not have images. Contributor in this case refers to any/all of the following: editors, authors, contributors, translators, illustrators, reviewers. 

Text beneath these profile images should say: "Learn more about the creator(s) of this book" and would link to the contributors front matter page, if it exists.

Should resemble this PoC from Rebus Community:
![Screenshot from 2021-06-21 11-31-53](https://user-images.githubusercontent.com/13485451/122810532-521bc600-d284-11eb-9955-f3ed119f0452.png)

**Comment by richard015ar** [comment]
## Dalcin & Ricardo team
### Remaining work
- Clear the url & rich text fields in the add-tag form right after the contributor is saved
- Add and handle profile picture field
- Match the profile fields to populate the contributors ones. It must happen when:
  - a new book is created (the book's creator is the new default contributor)
  - a new user is created by matching a existing one and adding it as contributor or greater role
  - a current user associated to the book and the role is changed to contributor or greater role
- Add unit tests
- Test manually with the other team changes

**Comment by SteelWagstaff** [comment]
End of Hackathon update:
WIP branches: https://github.com/pressbooks/pressbooks/tree/contributorsHackathon + https://github.com/pressbooks/pressbooks-book/tree/hackathon-contributors

TODO: 
* Add and handle profile picture field [Ricardo will add WIP to new branch]
* Fix contributor creation when an existing user is added to book
* Check that contributor is created when subscriber receives more powerful role
* Add unit tests
* Build the new 'contributor' page mocked up here: https://app.moqups.com/in6bz4aHlT/edit/page/ad623ec9e (with for loops)
* Build new 'contributors' block for book home page using spec: https://app.moqups.com/in6bz4aHlT/edit/page/a478e80df

**Comment by richard015ar** [comment]
Progress on profile picture in `hackathon-contributorProfilePicture` branch:

https://user-images.githubusercontent.com/13248424/128247043-b52358ee-3290-410c-85ef-7b47bbfe384f.mp4


Pending:
- remove fields after add (it doesn't work anymore after add the upload handler)
- Styling
- Force size (square). Now it's using thumbnail by default (there is a progress at the backend level, but it needs to be improved)

**Note**: _the plugin that Ned suggested won't work because it's for avatars, and it's a custom field (each user will have different pictures for different books, instead a user metadata - avatar for all books)_
