### ISSUE TITLE
Improve default covers & cover upload behaviour

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2097]
**Feature Description:**
- [x] Replace typewriter generic image with beautiful generic image https://github.com/pressbooks/ideas/issues/365
- [x] Improve image upload prompt text on book info page. See https://github.com/pressbooks/pressbooks/issues/2195#issuecomment-843587220. Current text reads: "Cover Image should be 1:1.5 aspect ratio. Recommended dimensions are 2500px × 3750px, maximum size is 2MB. NOTE: This cover will be included in your ebook files but not your PDF export. Read more [here](https://guide.pressbooks.com/chapter/how-to-design-your-book-cover/).": https://github.com/pressbooks/pressbooks/blob/3217c734b9f3d25d840c247a5ac5b16b6c1698cb/inc/image/namespace.php#L407
New text should read "This cover image will be displayed on the webbook home page and used as the internal cover in ebook exports. This image must be taller than it is wide (recommended ratio 1.33:1) and works best with a height between 800 and 1200px. Our guide includes [more advice on designing book covers](https://guide.pressbooks.com/chapter/how-to-design-your-book-cover/)." 
- [x] Force size dimensions upon upload (no wide covers!): https://github.com/pressbooks/pressbooks/blob/15162ce1d5093aad1479301d0c58fc5c90c2bda6/inc/admin/metaboxes/namespace.php#L96-L105
- [x] Change “Promote your book, set individual chapters privacy below” copy to desired text (include link to ‘pre-publication checklist’): https://github.com/pressbooks/pressbooks/blob/15162ce1d5093aad1479301d0c58fc5c90c2bda6/templates/admin/organize.php#L47

Context: https://docs.google.com/document/d/1b-YsRqRERAEsz3hwNWAT24CGgt-lL84Ee5BQ3PsEp9s/edit#bookmark=id.75mgimxkox5l

**Comment by hughmcguire** [comment]
* Can we autogenerate (without user input) so that the generic cover has title /author info.
*  Force size dimension can =  crop/adjust automatically

**Comment by SteelWagstaff** [comment]
@LeighKP please provide desired text for cover upload prompt and public/private on organize page: https://app.asana.com/0/1182991497694215/1200662475465253/f when convenient for you.

**Comment by LeighKP** [comment]
Those two copy requests will be separate on my end. You will receive Public/private first and cover upload prompt at a later date.

**Comment by LeighKP** [comment]
public/private copy:

Public — Anyone with the link can see your book. If your book's metadata meets a set of criteria, it will be listed in Pressbooks Directory. Individual chapters can be set to private.
_(hyperlink to Directory if possible)_

Private — Only users you invite can see your book, regardless of individual chapter visibility.

**Comment by LeighKP** [comment]
Simpler copy for cover image:

"This image will be displayed as the book cover. It will appear on the webbook homepage and as the internal cover for ebook exports. For best results, cover images should be [...] by [...] pixels."

Some problems: 
What is the best result cover size? The aspect ratio is too much to calculate and leaves too much for interpretation.
What is an _internal_ cover?
