### ISSUE TITLE
Improve in-book search experience

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2270]
- [ ] Make sure that the search covers title and content for front matter, back matter, parts, chapters, glossary terms, footnotes, contributors, and titles
- [ ] Add support for booleans and literal strings " "  
- [ ] Improve how search results are displayed (relevancy ranging instead of reverse chronological order, highlight first occurance of word [keyword in context type displays]
- [ ] Allow users to access search bar from table of contents

See several related tickets, including https://github.com/pressbooks/ideas/issues/350, https://github.com/pressbooks/pressbooks/issues/2200, https://github.com/pressbooks/pressbooks/issues/2150

**Comment by arzola** [comment]
This issue has been automatically closed as part of an organization-wide backlog review.

**Reason:** This issue was created 4y 7m ago with no updates in the last 4y 5m.

If this is still relevant, please feel free to reopen it with updated context. We appreciate your contributions and want to ensure our issue tracker stays actionable.

**Learn more:** https://pressbooks.community/t/announcement-automatic-closure-of-old-github-tickets/4542
