### ISSUE TITLE
FEATURE: Display contributor info on chapters, new back matter type, and book home page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2323]
As the creator of a book, I'd like to display more information about the people who made contributions to that book on individual chapters (for chapter authors), in the back matter (a 'contributor' back matter type/page which shows info about the books editors, authors, contributors, translators, illustrators, and reviweres), and on the book home page.

Some work on this task was started in a Pressbooks Hackathon. See https://github.com/pressbooks/pressbooks/issues/2096 for details.

TODO:
for V1 release
- [x] https://github.com/pressbooks/pressbooks-book/issues/833
- [x] #2311
- [x] https://github.com/pressbooks/pressbooks-book/issues/832
- [x] #2314
- [x] #2312
- [x] #1824 
- [x] #2231

future improvements:
- [ ] https://github.com/pressbooks/pressbooks-book/issues/831
- [ ] Allow users to associate their Pressbooks profile with an ORCID ID: #1500 + https://github.com/pressbooks/pressbooks-book/issues/433 
- [ ] https://github.com/pressbooks/ideas/issues/202 (needs refinement)

Context: https://docs.google.com/document/d/1b-YsRqRERAEsz3hwNWAT24CGgt-lL84Ee5BQ3PsEp9s/edit#bookmark=id.85aqxibgch6s
