### ISSUE TITLE
Improve export routines to more closely match Chicago Manual of Style recommendations

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2546]
See https://github.com/pressbooks/private/issues/77#issuecomment-982214307

## Book series information
> "**if the book is part of a series, it may include the title and volume number of the series, the name of the general editor of the series,** and sometimes the titles of previously published books in the series. If the book is the published proceedings of a symposium, the title of the symposium and the date it was held and other relevant details may appear on page ii. Alternatively, page ii might carry an illustration, called a frontis­piece [we don't currently support frontispieces]
- [ ] Add a new book info field for 'General Series Editor(s)' just below Series Title & Series Number
- [ ] If a book has a series title entered in the book metadata, print it on the recto page between the half title and title pages along with the series number and general series editor(s) [if provided 

## Book edition information
- [ ] Add a new book info field for 'Edition' 
- [ ] If a book includes an edition number, print it on the title page between the title/subtitle and author's name

## Title page adjustments
- [ ] Change the title page so that it only prints the names of **authors**, **editors** 'Edited by ...', and **translators** 'Translated by'. Remove **contributors** from appearing on the book's title page

## Copyright page adjustments
> Self-published authors are encouraged to in­clude, at a minimum, a copyright statement and a list of any assigned ISBNs, together with any other information that applies.
- [ ] Add copyright statement, e.g. `Copyright © 2021 by Steel Wagstaff` to top of copyright page, followed by license information and copyright notice. Derive values for this statement from publication date (if present in book info) or year of export (if not present) and copyright holder.
- [ ] Add ISBNs and DOI values to copyright page, if present in book info: `ISBN-13: ###-#########-# (print)` `ISBN-13: ###-#########-# (ebook)` and `DOI: https://doi.org/##.####/xxxxxx`

## Introduction adjustments
Chicago recommends that **Most introductions belong not in the front matter but at the beginning of the text, paginated with arabic numerals.** When we create new books, we automatically make front matter content with the type 'introduction'.  
- [ ] Change the auto-created front matter to have the title 'Preface' and use the front-matter type 'preface' 
- [ ] if the book does include a front matter introduction, change page numbering so that it uses roman numerals

## Back matter adjustments
- [ ] We include three separate back matter types: 'About the Author', 'Biographical Note', and 'Other books by author' which Chicago seems to consider one single type. Consider removing biographical note & other books by author and leaving just about the author. Existing back matter content classified as either of the removed types should be recategorized as 'About the author'.
- [ ] Create new back matter type called 'Illustration Credits'
- [ ] We don't do any automatic reordering of back matter (though we do for front matter). Create back matter ordering rules so that the following back matter content types (if they appear) display in this order:
1. Acknowledgments 
1. Appendix(es)
1. Chronology
1. Abbreviations
1. Glossary "A glossary usually precedes the notes and bibliography or reference list but may follow the notes, especially if terms listed in the glossary appear in the notes"
1. Notes "Endnotes, simply headed Notes, follow any appendix mate­rial and precede the bibliography or reference list (if there is one)."
1. Bibliography "A bibliography usually precedes the index and follows the notes, if any."
1. Contributors "A list of contributors may be appropriate for a work by many authors in which only the volume editor’s name appears on the title page. The list (usually headed Contributors) may appear in the front matter, but **the preferred location is in the back matter, immediately be­fore the index**." 
1. Illustration Credits
1. Index(es)
1. About the author/Biographical Note "A brief note on the author or authors (including any editors, compilers, and translators) lists previous publications and, if relevant, academic affiliation. **When such a note does not appear in the back matter (usually as the final element)**, it may appear in the front matter or, more commonly, on the back cover or on the inside flap of the dust jacket, according to the publisher’s preference."
1. Colophon "The last page of a specially designed and produced book occasionally contains a colophon—an inscription including the facts of production."

**Comment by eli-hu** [comment]
1. In addition to adding the book DOI to the copyright page, we would like to add the chapter DOIs at the start of each chapter if the book has DOIs at the chapter level.
2. I noticed this is labeled as an Epic. In your project workflow, would you typically create individual GitHub issues for the 12 subtasks of this epic? (in case one might want to tackle one of the subtasks)

**Comment by SteelWagstaff** [comment]
Hi @eli-hu yes, we'd probably create subtasks once we're ready to work on them. I don't have a task in our backlog to display the DOI at the start of the chapter in our exports. You could create one in https://github.com/pressbooks/ideas if you wanted to propose something for us to look at and potentially work on sooner?

**Comment by SteelWagstaff** [comment]
Note from support:
> Some print on demand partners (i.e. Lulu) now require all book interior PDF files to contain ISBN numbers. In the past, adding the ISBN number and barcode on the cover file was sufficient.

**Comment by MichSpieler** [comment]
Adding ISBN numbers to the metadata of export files (EPUB and PDF) was also requested by a network manager. ([Link to ticket](https://pressbooks.zendesk.com/agent/tickets/24082) for Support staff)

**Comment by MichSpieler** [comment]
A network manager has requested that Editors appear (as well as Contributors) in PDF exports. ([Link to request](https://pressbooks.zendesk.com/agent/tickets/25715) for PB Support Staff)

**Comment by arzola** [comment]
This issue has been automatically closed as part of an organization-wide backlog review.

**Reason:** This issue was created 4y 3m ago with no updates in the last 8m.

If this is still relevant, please feel free to reopen it with updated context. We appreciate your contributions and want to ensure our issue tracker stays actionable.

**Learn more:** https://pressbooks.community/t/announcement-automatic-closure-of-old-github-tickets/4542
