### ISSUE TITLE
Contributor Feature Improvements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2557]
Previous work: https://github.com/pressbooks/pressbooks/issues/2323
Context: https://docs.google.com/document/d/1b-YsRqRERAEsz3hwNWAT24CGgt-lL84Ee5BQ3PsEp9s/edit#bookmark=id.85aqxibgch6s

future improvements:

- [ ]  Display new 'contributors' block on book home page pressbooks-book#831
- [ ]  Allow users to associate their Pressbooks profile with an ORCID ID: [Research] Add ORCiD support for Pressbooks users #1500 + Add ORCID metadata for contributors pressbooks-book#433
- [ ]  Contributor Enhancements for Book Info  ideas#202 (needs refinement)

**Comment by arzola** [comment]
This issue has been automatically closed as part of an organization-wide backlog review.

**Reason:** This issue was created 4y 2m ago with no updates in the last 4y 2m.

If this is still relevant, please feel free to reopen it with updated context. We appreciate your contributions and want to ensure our issue tracker stays actionable.

**Learn more:** https://pressbooks.community/t/announcement-automatic-closure-of-old-github-tickets/4542
