### ISSUE TITLE
Refinements to new network manager checklist

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3384]
To fix before release:
- [x] Resolve caching issues that prevent congrats page from appearing and saved checklist items from being stored/remembered
- [x] Move the survey out of the congratulations page and make it the last step in the checklist
- [x] Make sure that link to Network Options page has graceful fallback for open source users (points to `https://NETWORK.URL/wp-admin/network/settings.php` instead of `https://NETWORK.URL/wp-admin/network/settings.php?page=pb_network_analytics_options`)
- [x] Revise Google Analytics step to say 'Learn about Analytics Options' and link them to the revised guide chapter
- [x] Add OIDC configuration as one of the SSO options (akin to how we currently handle SAML & CAS)
- [x] Revise network manager guide chapter about Koko Analytics (https://networkmanagerguide.pressbooks.com/chapter/view-page-visit-and-referrer-statistics/ as starting place) to better explain both analytics options Pressbooks supports (Koko & GA) and the pros/cons of each). 
- [x] Add required .env variables to all relevant networks

**Comment by SteelWagstaff** [comment]
Ideal guide chapter doesn't exist yet, but link can be updated if/when it does.

**Comment by arzola** [comment]
I sent a friendly commit to solve the cache issue when checklist items are stored

**Comment by SteelWagstaff** [comment]
Changes have been pushed to dev and staging networks and should be deployed and ready for testing shortly.

**Comment by tw77** [comment]
One thing I'm noticing on Staging when testing as a network manager user: 

When I check a box for the first time and quickly navigate away from the Administer Network dashboard (to 'My Books' / the user dashboard), when I return to the Administer Network dashboard, the box is unchecked.

It's only when I check the same box for a second time, navigate away, and navigate back that the box stays as checked from then on.

**Update:** this was due to navigating away very quickly, but doesn't occur in other situations, see https://github.com/pressbooks/pressbooks/issues/3384#issuecomment-1623712259

**Comment by cmurtagh** [comment]
> I sent a friendly commit to solve the cache issue when checklist items are stored

If that doesn't work, let's send a hostile commit.

**Comment by tw77** [comment]
If you move as quickly as possible to a different page and back after checking a box, the checked state of the box may not have not saved, or the background-color #D4D4D4 for the checked `<li>` may not have saved. But if you reload or refresh the page, the changes you made will have saved. Encountering this delay in saving only occurs in this unique scenario of moving very quickly away from and back to the checklist, and is solved with page reload. Caching works reliably and as expected, with checklist state being saved for the network as a whole, appearing consistently for multiple super admin / network manager users. Congrats page appears as expected.

**Comment by tw77** [comment]
Chapter prepared at this [private link](https://pressbooks.pub/networkmanagerguide/chapter/review-analytics-options/). Once approved, its text can be copied and pasted replacing https://networkmanagerguide.pressbooks.com/chapter/view-page-visit-and-referrer-statistics/. Permalink should be kept the same (or if changed, a redirect set up).

**Comment by SteelWagstaff** [comment]
Guide chapter looks good to me. Let's ask Amy for review and if good, I think we're ready to deploy!

Env variables will be sent seperately to ops team.

**Comment by tw77** [comment]
Revised guide chapter published at https://networkmanagerguide.pressbooks.com/chapter/view-page-visit-and-referrer-statistics/, can be linked from checklist.

**Comment by SteelWagstaff** [comment]
Deployed to production networks!
