### ISSUE TITLE
Enhanced (Meta?) Search Endpoint For Books

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#807]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Related to: https://github.com/pressbooks/pressbooks/issues/789, https://github.com/pressbooks/pressbooks/issues/788

Todo:

Come up with a descriptive endpoint name.  

Extend [Books Controller](https://github.com/pressbooks/pressbooks/blob/dev/inc/api/endpoints/controller/class-books.php). 

Feature parity with [AP1 V1 parameters](http://pressbooks.dev/api/v1/docs#parameters). [Code is here](https://github.com/pressbooks/pb-api).

To discuss:

+ What other metadata do we want to search? 
+ Can we document the params via OPTIONS programatically?

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.7.5
PHP: 7.1
