### ISSUE TITLE
Clone custom section meta

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#950]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

We should add handle importing any custom meta that is present in the front matter/chapter/back matter `meta` key during clone operations. Prerequisite: it would have to be available, which necessitates `register_meta()` being called for each custom metadata key (see: https://github.com/pressbooks/pressbooks/blob/dev/inc/posttype/namespace.php#L216-L257).

### Steps to Reproduce

1. Clone a book with custom front matter/chapter/back matter metadata.

**Expected behavior:** The extra fields are cloned.

**Actual behavior:** They aren't because they aren't being added to the `/metadata` endpoint.

### System Information

Pressbooks: 4.4-dev
WordPress: 4.8.
PHP: 7.1

**Comment by greatislander** [comment]
Note: must ensure that we don't clone core metadata when this happens. So there needs to be an exclusion list.

**Comment by greatislander** [comment]
Works?

**Comment by greatislander** [comment]
@monkecheese You had asked about this—I've tested and the only step to ensure that metadata associated with a chapter is cloned is to register the metadata so that it appears in the REST API (it Just Works™ after that's done). So, for example, say you've added a custom field called `lumen_test_id` to your chapters, you'd add this code to register it for the REST API ([see here](https://developer.wordpress.org/reference/functions/register_meta/) for full docs):

```
add_action( 'init', function() {
    register_meta( 'post', 'lumen_test_id', [
        'show_in_rest' => true,
        'single' => true, // False if multiple values are supported
        'type' => 'string',
    ] );
} );
```

Your metadata will now be cloned along with any chapter(s) where it's present.

**Comment by bessfernandez** [comment]
Hi there,

Finally looking at this 9 months later! Adding that `register_meta` worked great for seeing the field in the `meta` response for Pressbooks..  However the metadata still isn't getting picked up by the cloning. I believe this is due to use using our own meta boxes, not just adding a field to the PB specific meta boxes. So I don't see the field in the metadata response: `https://localhost/testsite/wp-json/pressbooks/v2/chapters/5/metadata/` . I can see how Pressbooks returns the meta fields like `pb_title` but since we are using our own meta boxes within WP, Is there a way to also get our own meta information exposed in the `/metadata` response easily.. or am I misunderstanding how clone would pick that meta data up? Thanks so much!

**Comment by greatislander** [comment]
@bessfernandez Assuming you've registered your own meta fields using `register_meta`, they would not appear in the `/metadata` endpoint, but rather in the chapter endpoint, i.e.:

https://book.pressbooks.com/wp-json/pressbooks/v2/chapters/4

```javascript
"meta": {
  "pb_show_title": "on",
  "pb_short_title": "Context, Not Container",
  "pb_subtitle": "",
  "pb_authors": [
    "hugh-mcguire",
    "brian-oleary"
   ],
  "pb_section_license": ""
}
```

Are you seeing your custom fields in that endpoint? If so, we can proceed to debugging the cloning routine.

**Comment by bessfernandez** [comment]
I accidentally said it was being cloned above, I meant it *wasn't*.. I edited it ;)

**Comment by greatislander** [comment]
Hi @bessfernandez, sorry for the delay in responding. We have been busy wrapping up our end of year releases. I'm going to reopen this for further investigation (cc @monkecheese).

**Comment by monkecheese** [comment]
I'm going to attempt to summarize the issue here so that I can be sure I'm understanding this correctly.

It was originally thought that registering the custom meta data so that it appears in the REST API would make it so that metadata would be cloned with the contents of a book when using PB Clone.

@bessfernandez discovered in her testing that the custom meta data appears under `meta` in the JSON response, but when a book is cloned, the metadata still does not carry over.  Is that correct?

@greatislander, I am going to try to replicate the issue locally to confirm the behavior.

**Comment by greatislander** [comment]
@monkecheese Yes, that's correct.

**Comment by monkecheese** [comment]
Okay, I can confirm that registering the meta data _doesn't_ Just Work™.

I am able to see the registered meta data in the JSON response, which looks like this:

```
meta: {
...
_candela_citation: "[{"type":"copyrighted_video","description":"Test attribution","author":"Mr John Cleese","organization":"Ministry of Silly Walks","url":"lifeofbrian.com","project":"Mayhem","license":"cc-by-nc","license_terms":""}]",
pb_show_title: "on",
pb_short_title: "",
pb_subtitle: "",
pb_authors: [ ],
pb_section_license: ""
},
...
```

When we clone the book using the PB clone feature, and set it to "Public", the metadata we're expecting doesn't appear in the editor.  Even more odd, the chapter with the meta data I'm expecting doesn't appear in the JSON response at all (but does exist when I navigate to that page).  The other strange behavior is what gets returned in the JSON response for the cloned book on all chapters:

```
meta: {
_candela_citation: "false",
pb_show_title: "on",
pb_short_title: "",
pb_subtitle: "",
pb_authors: [ ],
pb_section_license: ""
},
```

Our custom metadata (in this case `_candela_citation` is set to `false` on the cloned book.

Hopefully this is illuminating.  Happy to continue digging, and am all ears for feedback or clarifying questions.

**Comment by connerbw** [comment]
Please share your `register_meta` code. I'd be  interested in the `sanitize_callback` part of your code.

https://codex.wordpress.org/Function_Reference/register_meta

**Comment by connerbw** [comment]
Can you confirm you are registering on init? Ie. 

`add_action( 'init', '\your\register_meta_functions_here' );`

**Comment by connerbw** [comment]
> I am going to try to replicate the issue locally to confirm the behavior.

[If you have xdebug setup](https://docs.pressbooks.org/local-development/phpstorm-configuration/#xdebug), set some breakpoints here:

![image](https://user-images.githubusercontent.com/812192/51210381-ac104880-18e0-11e9-8095-9ec96a6fac12.png)

**Comment by monkecheese** [comment]
> Please share your register_meta code. I'd be interested in the sanitize_callback part of your code.

@connerbw , I essentially copy/pasta'd what @greatislander suggested earlier in this thread (replacing `lumen_test_id` with `_candela_citation`).  I haven't tried doing anything with sanitize_callback yet.

**Comment by connerbw** [comment]
Can you share a URL to a public book, somewhere on the internet, that I could point to and clone?

If the book [has meta keys visible in the REST-API json](https://github.com/pressbooks/pressbooks/issues/950#issuecomment-442980657), I could narow down the problem rather quickly...

**Comment by monkecheese** [comment]
Sure thing @connerbw.  I had spun up a sandbox on our hosting provider last week and have been digging into this issue on there.  Here's a book that is set to public and should be clone-able.

https://bradbox-candela.pantheonsite.io/userguide/

And here is the chapters endpoint for that book (in case that's helpful).

https://bradbox-candela.pantheonsite.io/userguide/wp-json/pressbooks/v2/chapters

**Comment by connerbw** [comment]
# Shorter Version

Works for me:

```php
add_action( 'init', function() {
	register_meta( 'post', '_candela_citation', [
		'show_in_rest' => true,
		'single' => true,
		'type' => 'string',
	] );
} );
```

![image](https://user-images.githubusercontent.com/812192/51269220-e4229480-198f-11e9-8350-1e030b355367.png)

Source: https://bradbox-candela.pantheonsite.io/userguide/wp-json/pressbooks/v2/chapters/138

# Longer Version

[Ignore my previous comment.](https://github.com/pressbooks/pressbooks/issues/950#issuecomment-454553926) It has to do with cloning bib.schema.org json, located here:

https://bradbox-candela.pantheonsite.io/userguide/wp-json/pressbooks/v2/chapters/138/metadata

Instead. Look at these three lines:

```php
$request = new \WP_REST_Request( 'POST', "/pressbooks/v2/$endpoint" );
$request->set_body_params( $section );
$response = rest_do_request( $request )->get_data();
```

[Source](https://github.com/pressbooks/pressbooks/blob/f0f724eea3374635027a3bed814fc54571981a78/inc/class-cloner.php#L509)

Particularly the `$response` variable. I strongly suspect you've got some other PHP doing stuff somewhere outside of Pressbooks?

To debug, do something like.

```
```php
add_action( 'init', function() {
	register_meta( 'post', '_candela_citation', [
		'show_in_rest' => true,
		'single' => true,
		'type' => 'string',
		'sanitize_callback' => function ( $v ) {
			// Your error logging mechanism here
			return $v;
		},
	] );
} );
```

Make sure the code snippet is running on both the source and the destination.

Make sure the file that contains the code snippet is being loaded when cloning. Maybe it's not?

And so on...
